name: Static analysis

on: [ 'push', 'pull_request' ]

jobs:
  static-analysis:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.2

      - name: Install Dependencies
        run: composer install --no-interaction --prefer-dist --optimize-autoloader

      - name: Run Linter
        run: composer run-script cs-check

      - name: Run PHPStan
        run: composer run-script phpstan